homework-08/linked_on_COMPLETE/config/routes.rb
Rails.application.routes.draw do

  root 'home#home'

  get '/login' => 'sessions#new' # login page
  post '/login' => 'sessions#create' # login form POSTs here; authentication logic
  get '/logout' => 'sessions#destroy' # logout and redirect to root

  resources :users
  resources :companies
  resources :skills

end

homework-08/linked_on_COMPLETE/app/models/company.rb
class Company < ActiveRecord::Base

  has_many :users

end

homework-08/linked_on_COMPLETE/app/models/skill.rb
class Skill < ActiveRecord::Base
	has_many :UsersSkills
	has_many :users, through: :UsersSkills
end

homework-08/linked_on_COMPLETE/app/models/user.rb
class User < ActiveRecord::Base
  
  belongs_to :company
  has_many :UsersSkills
  has_many :skills, through: :UsersSkills

  has_secure_password # AR method to activate bcrypt

  # column called password_digest, which is a string
  # $ rails g migration add_password_digest_to_users

end

homework-08/linked_on_COMPLETE/app/models/users_skill.rb
class UsersSkill < ActiveRecord::Base
	belongs_to :skill
	belongs_to :user
end

homework-08/linked_on_COMPLETE/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception

  def current_user
    if session[:user_id]
      @current_user ||= User.find(session[:user_id])
    end
  end
  helper_method :current_user

  def authorize
    redirect_to '/' if !current_user
  end

end

homework-08/linked_on_COMPLETE/app/controllers/companies_controller.rb
class CompaniesController < ApplicationController

  before_action :authorize

  def new
    @company = Company.new
  end

  def create
    @company = Company.new(company_params)

    if @company.save
      redirect_to '/'
    else
      render :new
    end
  end

private

  def company_params
    params.require(:company).permit(:name)
  end

end

homework-08/linked_on_COMPLETE/app/controllers/home_controller.rb
class HomeController < ApplicationController

  def home
    @companies = Company.all
    @users = User.all
    @skills = Skill.all
  end

end

homework-08/linked_on_COMPLETE/app/controllers/sessions_controller.rb
# app/controllers/sessions_controller.rb

class SessionsController < ApplicationController

  def new
  end


  # authentication logic and cookie stuff
  def create
    @user = User.find_by(email: params['email'])

    if @user && @user.authenticate(params['password'])
      session[:user_id] = @user.id

      flash[:message] = "Login successful!"

      redirect_to '/'
    else
      flash[:message] = "Incorrect Username or Password. Please try again."

      render :new
    end
  end


  def destroy
    session[:user_id] = nil
    redirect_to '/'
  end

end

homework-08/linked_on_COMPLETE/app/controllers/skills_controller.rb
class SkillsController < ApplicationController
	def new
		@skills = Skill.new
	end

	def create
		@skills = Skill.new(skill_params)

		if @skills.save
			redirect_to '/'
		else
			render :new
		end
	end

private
	def skill_params
		params.require(:skill).permit(:name)
	end
end

homework-08/linked_on_COMPLETE/app/controllers/users_controller.rb
class UsersController < ApplicationController

  def new
    @user = User.new
    @companies = Company.all
  end

  def create
    @user = User.new(user_params)

    if @user.save
      redirect_to '/'
    else
      render :new
    end
  end

private

  def user_params
    params.require(:user).permit(:name, :email, :company_id, :password, :password_confirmation)
  end

end

homework-08/linked_on_COMPLETE/app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>LinkedOn</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>

  <% if current_user %>
    You are currently logged in as <%= current_user.name %> | <%= link_to 'Logout', '/logout' %>
  <% else %>
    You are not logged in | <%= link_to 'Login', '/login' %>
  <% end %>

  <% if flash[:message] %>
    <b><%= flash[:message] %></b>
  <% end %>

<%= yield %>

</body>
</html>

homework-08/linked_on_COMPLETE/app/views/users/new.html.erb
<h1>Signup</h1>

<%= form_for @user do |f| %>

  <%= f.label :name %>
  <%= f.text_field :name %>
  <br><br>
  <%= f.label :email %>
  <%= f.text_field :email %>
  <br><br>

  <%= f.label :password %>
  <%= f.password_field :password %>
  <br><br>

  <%= f.label :password_confirmation %>
  <%= f.password_field :password_confirmation %>
  <br><br>



  <%= f.label :skills %>
  <% Skill.all.each do |s| -%>
      <div>
        <%= check_box_tag :skill_ids, s.id, @user.skills.include?(s), :name => 'user[s_ids][]' -%>
        <%= label_tag :skill_ids, s.name -%>
      </div>
    <% end -%>
  <br><br>

  <%= f.submit 'Signup' %>

<% end %>