homework-07/kelp/config/routes.rb
Rails.application.routes.draw do
  root 'restaurants#index'

  resources :restaurants
  resources :reviews

end

homework-07/kelp/app/models/restaurant.rb
class Restaurant < ActiveRecord::Base
	has_many :reviews
end

homework-07/kelp/app/models/review.rb
class Review < ActiveRecord::Base
	belongs_to :restaurant
end

homework-07/kelp/app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

homework-07/kelp/app/controllers/restaurants_controller.rb
class RestaurantsController < ApplicationController
	def index
		@restaurants = Restaurant.all
	end

	def show
		@restaurants = Restaurant.find(params[:id])
	end

	def new
		@new_restaurant = Restaurant.new
	end

	def create
		@new_restaurant = Restaurant.new(restaurant_params)

		if @new_restaurant.save
			redirect_to '/'
		else
			render :new
		end
	end

private
	def restaurant_params
		params.require(:restaurant).permit(:name, :address)
	end
end

homework-07/kelp/app/controllers/reviews_controller.rb
class ReviewsController < ApplicationController
	def new
		@review = Review.new
		@restaurant = Restaurant.find(params[:rest_id])
	end

	def create
		@review = Review.new(review_params)

		if @review.save
			redirect_to restaurant_path(@review.restaurant)
		else
			render :new
		end
	end

private
	def review_params
		params.require(:review).permit(:body, :author, :restaurant_id)
	end
end

homework-07/kelp/app/views/restaurants/index.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Kelp</title>

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/sticky-footer/sticky-footer.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Begin page content -->
    <div class="container">
      <div class="page-header">
        <h1>Kelp</h1>
      </div>
      <p class="lead"><%= link_to 'Join Kelp', new_restaurant_path %>
      <% @restaurants.each do |r| %>
      <p><%= link_to r.name, restaurant_path(r) %></p>
      <% end %>
    </div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">&copy; Steven Brand</p>
      </div>
    </footer>


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

homework-07/kelp/app/views/restaurants/new.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Add Your Restaurnt | Kelp</title>

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/sticky-footer/sticky-footer.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Begin page content -->
    <div class="container">
      <div class="page-header">
        <h1>Add Your Restaurant</h1>
      </div>
      <%= form_for @new_restaurant do |f| %>
      <div class="form-group">
        <%= f.label :name %>
        <%= f.text_field :name, class: 'form-control', placeholder: 'Name of your sushi spot' %>
      </div>

      <div class="form-group">
        <%= f.label :address %>
        <%= f.text_field :address, class: 'form-control', placeholder: "What's your address?" %>
      </div>

        <%= f.submit 'Join Kelp!', class: 'btn btn-success' %>
        <% end %>
    </div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">&copy; Steven Brand</p>
      </div>
    </footer>


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>

homework-07/kelp/app/views/restaurants/show.html.erb
<!DOCTYPE html>
<html lang="en">
  <head>
    <meta charset="utf-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1">
    <!-- The above 3 meta tags *must* come first in the head; any other head content must come *after* these tags -->
    <meta name="description" content="">
    <meta name="author" content="">
    <link rel="icon" href="../../favicon.ico">

    <title>Restaurant Info | Kelp</title>

    <!-- Bootstrap core CSS -->
    <link href="http://getbootstrap.com/dist/css/bootstrap.min.css" rel="stylesheet">

    <!-- Custom styles for this template -->
    <link href="http://getbootstrap.com/examples/sticky-footer/sticky-footer.css" rel="stylesheet">

    <!-- Just for debugging purposes. Don't actually copy these 2 lines! -->
    <!--[if lt IE 9]><script src="../../assets/js/ie8-responsive-file-warning.js"></script><![endif]-->

    <!-- HTML5 shim and Respond.js for IE8 support of HTML5 elements and media queries -->
    <!--[if lt IE 9]>
      <script src="https://oss.maxcdn.com/html5shiv/3.7.2/html5shiv.min.js"></script>
      <script src="https://oss.maxcdn.com/respond/1.4.2/respond.min.js"></script>
    <![endif]-->
  </head>

  <body>

    <!-- Begin page content -->
    <div class="container">
      <div class="page-header">
        <h1><%= @restaurants.name %></h1>
      </div>
      <p class="lead"><%= @restaurants.address %>

      <h3>Reviews:</h3>
      <% @restaurants.reviews.each do |r| %>
      <div class="panel panel-default">
        <div class="panel-body">
          <%= r.body %>
        </div>
        <div class="panel-footer"><%= r.author %></div>
      </div>
      <% end %>
      <p><%= link_to "Write a review for #{@restaurants.name}", new_review_path(rest_id: @restaurants.id) %></p>
      <p><%= link_to "Back To Home Page ", "/" %>
    </div>

    <footer class="footer">
      <div class="container">
        <p class="text-muted">&copy; Steven Brand</p>
      </div>
    </footer>


    <!-- IE10 viewport hack for Surface/desktop Windows 8 bug -->
    <script src="../../assets/js/ie10-viewport-bug-workaround.js"></script>
  </body>
</html>